"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import config, Csv, UndefinedValueError
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security settings loaded from environment variables via python-decouple.
# The application refuses to start if required variables are missing.

try:
    SECRET_KEY = config('SECRET_KEY')
except UndefinedValueError:
    raise ImproperlyConfigured(
        "The SECRET_KEY environment variable is not set. "
        "Please define it in your .env file or system environment."
    )

DEBUG = config('DEBUG', default=False, cast=bool)

try:
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
except UndefinedValueError:
    if not DEBUG:
        raise ImproperlyConfigured(
            "The ALLOWED_HOSTS environment variable is not set. "
            "It is required when DEBUG is False. "
            "Please define it as a comma-separated list in your .env file."
        )
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'peta',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Using SQLite for simplicity — no external database server required.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Cache configuration
# https://docs.djangoproject.com/en/6.0/topics/cache/

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'django_cache',
        'TIMEOUT': 300,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'peta.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Tambahkan baris ini biar Django ngebaca folder static yang posisinya di root projek
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static file cache headers (86400 seconds = 1 day)
# For production deployment with whitenoise, uncomment the following:
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Alternatively, use Django's built-in manifest storage:
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
#
# If using whitenoise, add to MIDDLEWARE (after SecurityMiddleware):
# 'whitenoise.middleware.WhiteNoiseMiddleware',
#
# WhiteNoise will serve static files with Cache-Control: max-age=86400 by default.
# For nginx/apache production setups, set cache-control headers in the server config:
#   location /static/ {
#       expires 1d;  # 86400 seconds
#   }
STATIC_FILE_CACHE_MAX_AGE = 86400  # 1 day in seconds
