# Generated by Django 5.2.14 on 2026-06-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='KabupatenJabar',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nama_kabupaten', models.CharField(max_length=255)),
                ('kemiskinan_persen', models.FloatField(help_text='Data dari file Kemiskinan.jpg')),
                ('kepadatan_penduduk', models.IntegerField(help_text='Data dari file kepadatan penduduk Jabar 2024.jpg')),
                ('ipm', models.FloatField(help_text='Data dari file Index Pembangunan Manusia (IPM).jpg')),
                ('provinsi', models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='beranda.provinsi')),
            ],
            options={
                'db_table': 'kabupaten_jabar',
            },
        ),
    ]
